# Generated by Django 6.0.2 on 2026-03-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(choices=[('engineer', 'Engineer'), ('electrician', 'Electrician'), ('painter', 'Painter'), ('mason', 'Mason'), ('screeder', 'Screeder'), ('pop_installer', 'POP Installer'), ('welder', 'Welder'), ('tiler', 'Tiler'), ('carpenter', 'Carpenter'), ('furniture_maker', 'Furniture Maker'), ('iron_bender', 'Iron Bender'), ('fabricator', 'Fabricator'), ('window_hood_installer', 'Window Hood Installer'), ('concrete_specialist', 'Concrete Specialist'), ('scaffolder', 'Scaffolder'), ('borehole_specialist', 'Borehole Specialist'), ('plaster_board', 'Plaster Board'), ('interlock', 'Interlock'), ('aluminium_work', 'Aluminium Work'), ('site_manager', 'Site Manager'), ('site_supervisor', 'Site Supervisor'), ('labourer', 'Labourer')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['skill', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
