# Generated by Django 6.0.2 on 2026-04-01 11:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_worker_remove_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['-rating', 'skill', 'name']},
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience in this skill', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is worker currently available?'),
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Rating from 0.0 to 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='skill',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('electrician', 'Electrician'), ('painter', 'Painter'), ('mason', 'Bricklayer / Mason'), ('screeder', 'Screeder'), ('pop_installer', 'POP Installer'), ('welder', 'Welder'), ('tiler', 'Tiler'), ('carpenter', 'Carpenter'), ('furniture_maker', 'Furniture Maker'), ('plumber', 'Plumber'), ('iron_bender', 'Iron Bender'), ('fabricator', 'Fabricator'), ('window_hood_installer', 'Window Hood Installer'), ('concrete_specialist', 'Concrete Specialist'), ('scaffolder', 'Scaffolder'), ('borehole_specialist', 'Borehole Specialist'), ('plaster_board', 'Plaster Board'), ('interlock', 'Interlock'), ('aluminium_work', 'Aluminium Work'), ('site_manager', 'Site Manager'), ('site_supervisor', 'Site Supervisor'), ('labourer', 'Labourer')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['skill', 'location'], name='contacts_wo_skill_b1024b_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['phone'], name='contacts_wo_phone_18b14c_idx'),
        ),
    ]
